# Generated by Django 3.2.8 on 2021-11-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manufacture', models.CharField(max_length=20)),
                ('release', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('data_type', models.IntegerField()),
            ],
            options={
                'db_table': 'component',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=20, null=True)),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('pci', models.IntegerField(blank=True, null=True)),
                ('fan', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('component_componenet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='component.component')),
            ],
            options={
                'db_table': 'case',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('system', models.CharField(blank=True, max_length=10, null=True)),
                ('fan_size', models.IntegerField(blank=True, null=True)),
                ('fan_thickness', models.IntegerField(blank=True, null=True)),
                ('connector', models.CharField(blank=True, max_length=20, null=True)),
                ('loudness', models.CharField(blank=True, max_length=30, null=True)),
                ('fan_faster', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('tdp', models.IntegerField(blank=True, null=True)),
                ('intel_socket', models.CharField(blank=True, max_length=100, null=True)),
                ('amd_socket', models.CharField(blank=True, max_length=100, null=True)),
                ('component_componenet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='component.component')),
            ],
            options={
                'db_table': 'cooler',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('component_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='component.component')),
                ('socket', models.CharField(blank=True, max_length=50, null=True)),
                ('generation', models.CharField(blank=True, max_length=50, null=True)),
                ('core', models.IntegerField(blank=True, null=True)),
                ('thread', models.IntegerField(blank=True, null=True)),
                ('thickness', models.IntegerField(blank=True, null=True)),
                ('basic_clock', models.CharField(blank=True, max_length=10, null=True)),
                ('max_clock', models.CharField(blank=True, max_length=10, null=True)),
                ('l2_cache', models.CharField(blank=True, db_column='L2_cache', max_length=10, null=True)),
                ('l3_cache', models.CharField(blank=True, db_column='L3_cache', max_length=10, null=True)),
                ('tdp', models.IntegerField(blank=True, db_column='TDP', null=True)),
                ('pcie', models.CharField(blank=True, db_column='PCIe', max_length=50, null=True)),
                ('memory_type', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_bus', models.IntegerField(blank=True, null=True)),
                ('memory_channel', models.IntegerField(blank=True, null=True)),
                ('has_graphic', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cpu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('component_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='component.component')),
                ('chipset', models.CharField(blank=True, max_length=20, null=True)),
                ('thickness', models.IntegerField(blank=True, null=True)),
                ('memory_type', models.CharField(blank=True, max_length=20, null=True)),
                ('memory_clock', models.IntegerField(blank=True, null=True)),
                ('memory_capacity', models.CharField(blank=True, max_length=10, null=True)),
                ('hdmi', models.CharField(blank=True, db_column='HDMI', max_length=10, null=True)),
                ('displayport', models.CharField(blank=True, db_column='DisplayPort', max_length=20, null=True)),
                ('monitor_support', models.IntegerField(blank=True, null=True)),
                ('required_power', models.IntegerField(blank=True, null=True)),
                ('used_power', models.CharField(blank=True, max_length=20, null=True)),
                ('power_port', models.CharField(blank=True, max_length=20, null=True)),
                ('power_case', models.CharField(blank=True, max_length=20, null=True)),
                ('width', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('interface', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'gpu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hdd',
            fields=[
                ('component_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='component.component')),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('interface', models.CharField(blank=True, max_length=30, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('buffer', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hdd',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mainboard',
            fields=[
                ('component_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='component.component')),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('socket', models.CharField(blank=True, max_length=20, null=True)),
                ('chipset', models.CharField(blank=True, max_length=20, null=True)),
                ('chipset_detail', models.CharField(blank=True, max_length=20, null=True)),
                ('cpu_count', models.IntegerField(blank=True, null=True)),
                ('formfactor', models.CharField(blank=True, max_length=40, null=True)),
                ('power', models.CharField(blank=True, max_length=30, null=True)),
                ('memory_type', models.CharField(blank=True, max_length=30, null=True)),
                ('memory_speed', models.CharField(blank=True, max_length=30, null=True)),
                ('memory_slot', models.IntegerField(blank=True, null=True)),
                ('memory_channel', models.IntegerField(blank=True, null=True)),
                ('memory_capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('graphic', models.CharField(blank=True, max_length=20, null=True)),
                ('vga_connect', models.CharField(blank=True, max_length=20, null=True)),
                ('pcie_hex', models.IntegerField(blank=True, null=True)),
                ('pcie_octa', models.IntegerField(blank=True, null=True)),
                ('pcie_quad', models.IntegerField(blank=True, null=True)),
                ('pcie_single', models.IntegerField(blank=True, null=True)),
                ('ssd_slot', models.IntegerField(blank=True, null=True)),
                ('sata_slot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mainboard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('component_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='component.component')),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('clock', models.CharField(blank=True, max_length=20, null=True)),
                ('timing', models.CharField(blank=True, max_length=20, null=True)),
                ('volt', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'memory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('output', models.CharField(blank=True, max_length=20, null=True)),
                ('certification', models.CharField(blank=True, max_length=20, null=True)),
                ('main_cable', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_cable', models.CharField(blank=True, max_length=20, null=True)),
                ('pcie_octa', models.CharField(blank=True, max_length=20, null=True)),
                ('pcie_hexa', models.CharField(blank=True, max_length=20, null=True)),
                ('sata', models.CharField(blank=True, max_length=20, null=True)),
                ('ide', models.CharField(blank=True, max_length=20, null=True)),
                ('component_componenet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='component.component')),
            ],
            options={
                'db_table': 'power',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ssd',
            fields=[
                ('component_component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='component.component')),
                ('formfactor', models.CharField(blank=True, max_length=20, null=True)),
                ('interface', models.CharField(blank=True, max_length=30, null=True)),
                ('capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('seq_read', models.CharField(blank=True, max_length=20, null=True)),
                ('seq_write', models.CharField(blank=True, max_length=20, null=True)),
                ('read_iops', models.IntegerField(blank=True, null=True)),
                ('write_iops', models.IntegerField(blank=True, null=True)),
                ('tbw', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ssd',
                'managed': True,
            },
        ),
    ]
