# Generated by Django 3.2.8 on 2021-12-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_auto_20211201_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='memory_bus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
