# Generated by Django 3.2.8 on 2021-12-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_rename_component_componenet_case_component_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooler',
            old_name='component_componenet',
            new_name='component_component',
        ),
        migrations.RenameField(
            model_name='power',
            old_name='component_componenet',
            new_name='component_component',
        ),
    ]
