# Generated by Django 3.2.8 on 2021-10-26 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('annotation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('explain', models.TextField()),
            ],
            options={
                'db_table': 'annotations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('estimations_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estimation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('evaluations_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('written', models.DateTimeField()),
            ],
            options={
                'db_table': 'evaluations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uses',
            fields=[
                ('uses_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.PositiveIntegerField()),
                ('game_genre', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('least_processor', models.CharField(blank=True, max_length=100, null=True)),
                ('least_graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('least_memory', models.CharField(blank=True, max_length=30, null=True)),
                ('rec_processor', models.CharField(blank=True, max_length=100, null=True)),
                ('rec_graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('rec_memory', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'uses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstimationHasComponent',
            fields=[
                ('estimation_estimations', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='estimate.estimation')),
            ],
            options={
                'db_table': 'estimation_has_component',
                'managed': False,
            },
        ),
    ]
