# Generated by Django 3.2.8 on 2021-11-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
        ('member', '0001_initial'),
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('evaluations_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('written', models.DateTimeField()),
                ('component_component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='component.component')),
                ('members_members', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member.members')),
            ],
            options={
                'db_table': 'evaluations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstimationHasComponent',
            fields=[
                ('estimation_estimations', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='estimate.estimation')),
                ('component_component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='component.component')),
            ],
            options={
                'db_table': 'estimation_has_component',
                'managed': True,
                'unique_together': {('estimation_estimations', 'component_component')},
            },
        ),
    ]
