# Generated by Django 3.2.8 on 2021-12-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_estimationhascomponent_evaluations'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmark',
            name='data_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='annotation_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uses',
            name='least_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uses',
            name='rec_memory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
