# Generated by Django 3.2.8 on 2021-10-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('likes_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('posts_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('content', models.TextField()),
                ('written', models.DateTimeField()),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reports_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reports',
                'managed': False,
            },
        ),
    ]
