# Generated by Django 3.2.8 on 2021-11-06 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('members_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('birth', models.DateTimeField()),
                ('question_type', models.IntegerField()),
                ('question_ans', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
    ]
