# Generated by Django 3.2.8 on 2021-10-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('members_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('birth', models.DateTimeField()),
                ('question_type', models.IntegerField()),
                ('question_ans', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
    ]
